#!/usr/bin/bash env
#command to install nginx on web server

sudo apt-get update
sudo apt-get installnginx
sudo ufw 'Nginx HTTP"

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx restart
