#!/usr/bin/bash env
# confifure a ufw firewall to block all incoming traffic
# allow for TCP ports 22, 80, 443

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status verbose
